# Generated by Django 3.1.7 on 2021-05-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=200)),
                ('isbn', models.IntegerField()),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('Book_Name', models.CharField(max_length=200)),
                ('isbn', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('Roll_Numner', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('Contact_Number', models.IntegerField()),
            ],
        ),
    ]
