# Generated by Django 3.1.7 on 2021-05-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Librarians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=200)),
                ('Roll_Numner', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('Contact_Number', models.IntegerField()),
                ('unique_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='IssueBook',
            new_name='IssueBooks',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
