# Generated by Django 3.1.7 on 2021-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20210526_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=200)),
                ('Author_Name', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
