# Generated by Django 3.1.7 on 2021-06-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_auto_20210603_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Librarian',
            new_name='Librarians',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
