# Generated by Django 3.1.7 on 2021-06-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20210603_2151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Librarians',
            new_name='Employee',
        ),
    ]
