# Generated by Django 3.1.7 on 2021-06-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_auto_20210603_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
