# Generated by Django 3.1.7 on 2021-06-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_auto_20210603_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone_numbers',
        ),
    ]
