# Generated by Django 3.1.7 on 2021-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_auto_20210603_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
