# Generated by Django 3.1.7 on 2021-06-03 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_auto_20210603_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Librarian_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
