# Generated by Django 3.1.7 on 2021-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_auto_20210603_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='Book_Name',
            new_name='BookName',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='Student_Name',
            new_name='StudentName',
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='issue_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
