# Generated by Django 3.1.7 on 2021-06-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_auto_20210617_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='BookName',
            new_name='Book_Name',
        ),
        migrations.RenameField(
            model_name='issuebook',
            old_name='StudentName',
            new_name='Student_Name',
        ),
    ]
