# Generated by Django 3.1.7 on 2021-06-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_auto_20210617_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='unique_id',
            new_name='uid',
        ),
    ]
