# Generated by Django 3.1.7 on 2021-06-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_auto_20210618_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='uid',
        ),
    ]
